// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxnwhsBvGDZBqnz6uBwev3atoi68481vg',
    appId: '1:597770023353:web:05d069de0de8cbc10bc668',
    messagingSenderId: '597770023353',
    projectId: 'fir-memo-app-19a38',
    authDomain: 'fir-memo-app-19a38.firebaseapp.com',
    storageBucket: 'fir-memo-app-19a38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQsdT89bdD2mxAqen37GakHItwrQqS4Ew',
    appId: '1:597770023353:android:f87b3ad318ee19f70bc668',
    messagingSenderId: '597770023353',
    projectId: 'fir-memo-app-19a38',
    storageBucket: 'fir-memo-app-19a38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCRLmr8HoWfBNCKyCcN4SveUVpkQ4G9VI',
    appId: '1:597770023353:ios:70186ceb5d63425e0bc668',
    messagingSenderId: '597770023353',
    projectId: 'fir-memo-app-19a38',
    storageBucket: 'fir-memo-app-19a38.appspot.com',
    iosClientId: '597770023353-6mbs4dv5l6eoakgq4bf04khuri2dv2t3.apps.googleusercontent.com',
    iosBundleId: 'com.example.memo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCRLmr8HoWfBNCKyCcN4SveUVpkQ4G9VI',
    appId: '1:597770023353:ios:70186ceb5d63425e0bc668',
    messagingSenderId: '597770023353',
    projectId: 'fir-memo-app-19a38',
    storageBucket: 'fir-memo-app-19a38.appspot.com',
    iosClientId: '597770023353-6mbs4dv5l6eoakgq4bf04khuri2dv2t3.apps.googleusercontent.com',
    iosBundleId: 'com.example.memo',
  );
}
